### ISSUE TITLE
[ERROR] Failed to resolve entry for package "@ngraveio/bc-ur". 

### ISSUE THREAD

**Issue by kagenkoda** [ngraveio/bc-ur#22]
[ERROR] Failed to resolve entry for package "@ngraveio/bc-ur". The package may have incorrect main/module/exports specified in its package.json.

This causing many upstream packages to fail vite builds. Related: https://github.com/anza-xyz/wallet-adapter/issues/909
- Vite
- React

Minimal Reproduction:

https://stackblitz.com/edit/vitejs-vite-7sysct?file=src%2FApp.tsx

**Comment by xardass** [comment]
Hi @kagenkoda please try v1.1.12

**Comment by kagenkoda** [comment]
works now! appreciate it
