### ISSUE TITLE
Dependencies need more work

### ISSUE THREAD

**Issue by Overtorment** [ngraveio/bc-ur#7]
Looks like this can be moved to dev dependencies:

```
    "@types/crc": "^3.4.0",
    "@types/sha.js": "^2.4.0",
    "assert": "^2.0.0",
```

This looks like its duplicated:

```
    "big-integer": "^1.6.48",
    "bignumber.js": "^9.0.1",
```

(`bignumber.js` is more favorable, its used more, developed more)

I didn't investigate, but just looking at it feels like they do the same thing:

```
    "@ellipticoin/cbor": "^1.0.4",
    "@iljucha/cbor": "^1.0.10",
    "cbor-sync": "^1.0.4",
    "cborg": "^1.0.4",
```

**Comment by xardass** [comment]
Thanks, we are looking into this

**Comment by antonispoulakis** [comment]
Thanks @Overtorment. All of those cbor libraries aren't needed, they are leftovers from testing.

Regarding the `big-integer` dependency, I will replace it with JS's native `BigInt`. `bignumber.js` can't be used in its place for our use case, as we need bitwise operations which it doesn't support.

**Comment by Overtorment** [comment]
i think `BigInt` is not supported by react-native

**Comment by antonispoulakis** [comment]
> i think `BigInt` is not supported by react-native

Yes, you're right; Totally forgot about react-native. 

After some testing, the only real alternative I can see using is [`JSBI`](https://www.npmjs.com/package/jsbi) which seems to be significantly faster than `big-integer` (12 seconds) and match the native `BigInt` performance (2.5-3 seconds) when running the tests. It's still an extra dependency, but at least it doesn't seem to have a performance hit.

Unless you have some better alternative in mind, I will merge the pr using `JSBI`.

**Comment by xardass** [comment]
@Overtorment v1.1.5 should resolve this issue.
